language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test-requirements.txt --use-mirrors"
before_script: "git fetch -a origin"
script: ./scripts/run_tests.sh
after_script: ./scripts/run_diff_cover.sh
